spring:
  application:
    name: api-gateway

server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
    register-with-eureka: false
  instance:
    preferIpAddress: true